name: Build and Push Docker Images

on:
  push:
    branches:
      - master # Se ejecuta cuando hay un push a la rama principal

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Descargar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 3: Build and Push Backend Image
      - name: Build and Push Backend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/soft-web:soft-back ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/soft-web:soft-back

      # Paso 4: Build and Push Frontend Image
      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/soft-web:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/soft-web:latest

      - name: Deploy to Railway
        run: |
          railway up --token ${{ secrets.RAILWAY_TOKEN }}
